services:
  - type: web
    name: ml-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: MODEL_VERSION
        value: "1.0"
      - key: API_TIMEOUT
        value: "30"
